export {
  failedTruckSchema,
  pendingTruckSchema,
  successTruckSchema,
  truckListingSchema,
  truckParseResultSchema,
  truckPriceSchema,
  type FailedTruck,
  type PendingTruck,
  type SmartStoreTable,
  type SuccessTruck,
  type TruckListing,
  type TruckParseResult,
  type TruckPrice,
} from './model'
